### ISSUE TITLE
Add Issue Labels support

### ISSUE THREAD

**Issue by rgreinho** [innovationnorway/terraform-github-repository#8]
I added the support for Issue Labels to the version 1.x of the module (i.e. for Terraform 0.11.x): https://github.com/rgreinho/terraform-github-repository/blob/1.x/examples/example-labels.tf

Would you be interested in a patch for this version?

**Comment by joakimhellum-in** [comment]
@rgreinho Yes, we would very much appreciate this contribution. Thanks alot!

**Comment by joakimhellum-in** [comment]
@rgreinho Your PR (#9) was included in version [1.4.0](https://github.com/innovationnorway/terraform-github-repository/releases/tag/v1.4.0) 🎉 Many thanks
